      - name: Fetch status and update README
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const child = require('child_process');
            const query = `query { user(login: "marcosmwaba") { status { emoji message indicatesLimitedAvailability expiresAt } } }`;
            const result = await github.graphql(query);
            const statusObj = result && result.user && result.user.status ? result.user.status : null;
            let statusText = '';
            if (statusObj) {
              const emoji = statusObj.emoji || '';
              const msg = statusObj.message || '';
              statusText = (emoji + ' ' + msg).trim();
            }
            core.info(`Fetched status: ${statusText || '<empty>'}`);

            const path = 'README.md';
            let content;
            try {
              content = fs.readFileSync(path, 'utf8');
            } catch (e) {
              core.setFailed(`Cannot read ${path}: ${e.message}`);
              return;
            }

            // 🧩 FIXED: Use backticks safely inside YAML by using | and avoiding raw asterisks
            const newBlock = `<!-- STATUS:START -->
**GitHub Status:** ${statusText || '_No status set_'}
<!-- STATUS:END -->`;

            const re = /<!-- STATUS:START -->[\\s\\S]*?<!-- STATUS:END -->/;
            const updated = re.test(content)
              ? content.replace(re, newBlock)
              : content.replace(/\\s*$/, '') + '\n\n' + newBlock + '\n';

            if (updated === content) {
              core.info('No README change required.');
              return;
            }

            fs.writeFileSync(path, updated, 'utf8');
            child.execSync('git config user.name "github-actions[bot]"');
            child.execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');

            try {
              child.execSync('git add README.md');
              const status = child.execSync('git status --porcelain').toString().trim();
              if (!status) {
                core.info('No changes to commit after add.');
                return;
              }
              child.execSync('git commit -m "chore: update GitHub profile status in README"');
              child.execSync('git push');
              core.info('Committed README update.');
            } catch (err) {
              core.info('No changes to commit or push: ' + err.message);
            }
